// cache 20260914j
/**
 * Vencedores Autopartes — embudo marca → línea → tipo → producto
 * brandLines: INR Catalogodepartes.pdf 2025 (no encoger).
 * fits: solo modelos del mismo COD/listado PDF; sin contaminación cruzada.
 */
(function (global) {
  "renault": [
    "R4",
    "R6",
    "R9",
    "R12",
    "R18",
    "R19",
    "R21",
    "Alaskan",
    "Captur",
    "Clio",
    "Express Taxi",
    "Duster",
    "Oroch",
    "Fluence",
    "Kangoo",
    "Koleos",
    "Kwid",
    "Laguna",
    "Logan",
    "Megane",
    "Sandero",
    "Scala",
    "Scenic",
    "Stepway",
    "Symbol",
    "Citius Taxi",
    "Trafic",
    "Twingo"
  ],
  "mazda": [
    "121",
    "323",
    "626",
    "Allegro",
    "B1600",
    "B2000",
    "B2200",
    "B2600",
    "BT-50",
    "CX-3",
    "CX-5",
    "CX-7",
    "Mazda2",
    "Mazda3",
    "Mazda5",
    "Mazda6",
    "MX-5",
    "MX-3",
    "MX-6"
  ],
  "chevrolet": [
    "Alto",
    "Astra",
    "Aveo",
    "Captiva",
    "Chevy C2",
    "Cobalt",
    "Corsa",
    "Cruze",
    "Epica",
    "Joy",
    "LUV",
    "D-Max",
    "NHR",
    "NKR",
    "NNR",
    "NPR",
    "NQR",
    "N200",
    "N300",
    "Onix",
    "Optra",
    "Rodeo",
    "Sail",
    "Sonic",
    "Spark",
    "Spark GT",
    "Sprint",
    "Swift",
    "Trailblazer",
    "Tracker",
    "Trooper",
    "Vitara",
    "Wagon R",
    "Super Carry",
    "Jimny",
    "Samurai"
  ],
  "hyundai": [
    "Accent",
    "Atos",
    "Azera",
    "Elantra",
    "Eon",
    "Excel",
    "Getz",
    "Grace",
    "i10",
    "Grand i10",
    "Grand Metro Taxi",
    "i25",
    "i30",
    "i35",
    "i40",
    "i45",
    "Porter",
    "Santa Fe",
    "Santro",
    "Sonata",
    "Starex",
    "Terracan",
    "Tucson",
    "Veloster",
    "Veracruz",
    "Vision"
  ],
  "kia": [
    "Besta",
    "Carnival",
    "Cerato",
    "K2500",
    "K2700",
    "Picanto",
    "Eko Taxi",
    "Ion",
    "Morning",
    "Pregio",
    "Pride",
    "Rio",
    "Sedona",
    "Sephia",
    "Spectra",
    "Sportage",
    "Soul",
    "Sorento",
    "Optima",
    "Master"
  ],
  "toyota": [
    "Avalon",
    "Camry",
    "Celica",
    "Coaster",
    "Corolla",
    "Corona",
    "Fortuner",
    "4Runner",
    "Hilux",
    "Land Cruiser",
    "Prado",
    "RAV4",
    "Starlet",
    "Tercel",
    "Yaris",
    "T100",
    "Tacoma",
    "Tundra",
    "TXL",
    "Burbuja"
  ],
  "nissan": [
    "Almera",
    "Altima",
    "Frontier",
    "Navara",
    "NP300",
    "Juke",
    "Kicks",
    "March",
    "Micra",
    "Murano",
    "Note",
    "Patrol",
    "Pathfinder",
    "Qashqai",
    "Sentra",
    "Tiida",
    "Urvan",
    "Versa",
    "X-Trail",
    "Xterra",
    "Sunny"
  ],
  "mitsubishi": [
    "Colt",
    "Lancer",
    "L200",
    "L200 Advancer",
    "L200 Sportero",
    "L300",
    "Montero",
    "Nativa",
    "Outlander"
  ],
  "ford": [
    "EcoSport",
    "Edge",
    "Escape",
    "Explorer",
    "Festiva",
    "Fiesta",
    "Fusion",
    "Laser",
    "Ranger"
  ],
  "suzuki": [
    "Grand Vitara",
    "Jimny",
    "Swift"
  ]
})(typeof window !== "undefined" ? window : globalThis);
