/**
 * Vencedores Autopartes — catálogo searchable (solo datos de PDFs oficiales).
 * Sin precios inventados. Cotización por WhatsApp.
 */
(function (global) {
  const WA_LINES = {
    pedales: "Hola estoy muy interesado en sus productos. Pedales",
    fuelles: "Hola estoy muy interesado en sus productos. Guardapolvos y fuelles",
    mezclas: "Hola estoy muy interesado en sus productos. Mezclas",
    general: "Hola estoy muy interesado en sus productos.",
  };

  const brands = [
    {
      id: "chevrolet",
      name: "Chevrolet",
      monogram: "C",
      tagline: "Pedales CV + guardapolvos eje y dirección",
      accent: "#F59E0B",
      highlights: ["Pedales CV-01…CV-04", "Guardapolvos eje L/C · L/R", "Fuelles dirección", "Spark · Aveo · Sail · LUV · D-Max"],
      vehicleTypes: ["liviano", "camioneta", "camion", "taxi"],
    },
    {
      id: "renault",
      name: "Renault",
      monogram: "R",
      tagline: "Línea más completa de fuelles y pedales",
      accent: "#FBBF24",
      highlights: ["Pedales CV-05", "Guardapolvos eje L/C · L/R", "Fuelle caja dirección", "Logan · Sandero · Clio · Duster"],
      vehicleTypes: ["liviano", "camioneta", "taxi"],
    },
    {
      id: "hyundai",
      name: "Hyundai",
      monogram: "H",
      tagline: "Pedales, taxi y fuelles de dirección",
      accent: "#F59E0B",
      highlights: ["Pedales CV-06…CV-09", "Hyundai Taxi / Atos", "Fuelle dirección i10", "Accent · Vision · Atos"],
      vehicleTypes: ["liviano", "taxi"],
    },
    {
      id: "kia",
      name: "Kia",
      monogram: "K",
      tagline: "Pedales y guardapolvos taxi / Picanto",
      accent: "#D97706",
      highlights: ["Pedales CV-06 · CV-07", "Picanto / Ekotaxi / Ion", "Refs 33103 · 33104", "Rio · Sportage · Sorento"],
      vehicleTypes: ["liviano", "taxi", "camioneta"],
    },
    {
      id: "mazda",
      name: "Mazda",
      monogram: "M",
      tagline: "Pedales CV + guardapolvos 626 / Mazda3",
      accent: "#F59E0B",
      highlights: ["Pedales CV-03 · CV-07", "626 NR / Asahi / Matsuri", "Mazda3 · Mazda5 · B2600", "Fuelle dirección MX-6"],
      vehicleTypes: ["liviano", "camioneta"],
    },
    {
      id: "nissan",
      name: "Nissan",
      monogram: "N",
      tagline: "Pedales camioneta y busetón",
      accent: "#FBBF24",
      highlights: ["Pedales CV-10 · CV-11", "Frontier · Urvan", "Busetón Nissan", "Rejilla / espiga"],
      vehicleTypes: ["camioneta", "bus"],
    },
    {
      id: "toyota",
      name: "Toyota",
      monogram: "T",
      tagline: "Pedales universales camioneta",
      accent: "#F59E0B",
      highlights: ["Pedales CV-12", "Prado · 4Runner", "Universal camionetas", "Mixto"],
      vehicleTypes: ["camioneta"],
    },
    {
      id: "mitsubishi",
      name: "Mitsubishi",
      monogram: "Mi",
      tagline: "Pedales CV-06 · L300",
      accent: "#D97706",
      highlights: ["Pedales CV-06", "L300", "Espiga / chevron"],
      vehicleTypes: ["liviano", "camioneta"],
    },
    {
      id: "mercedes-benz",
      name: "Mercedes-Benz",
      monogram: "MB",
      tagline: "Pedales bus / espiga CV-11",
      accent: "#F59E0B",
      highlights: ["Pedales CV-11", "Bus / Esplínder", "Espiga"],
      vehicleTypes: ["bus"],
    },
    {
      id: "suzuki",
      name: "Suzuki",
      monogram: "S",
      tagline: "Línea Chevy/Suzuki — Alto · Swift · Vitara",
      accent: "#FBBF24",
      highlights: ["Guardapolvos Alto · Swift", "Sprint SA310", "Vitara SE416", "Fuelles dirección"],
      vehicleTypes: ["liviano", "camioneta"],
    },
  ];

  /** @type {Array<object>} */
  const products = [
    // ——— PEDALES CV (primarios) ———
    {
      id: "cv-01",
      ref: "CV-01",
      type: "pedal",
      brand: "Chevrolet",
      brands: ["Chevrolet"],
      models: ["LUV 2300", "D-Max", "Dimax", "Trooper"],
      title: "Pedal freno y embrague — nervaduras horizontales",
      desc: "Forro 100% caucho. Nervaduras horizontales. Parque camioneta Chevrolet.",
      tags: ["freno", "embrague", "nervaduras horizontales", "camioneta"],
      synonyms: ["luv", "dmax", "d-max", "dimax", "trooper", "chevy", "chevrolet", "forro pedal"],
      waLine: "pedales",
      legacy: ["P009"],
    },
    {
      id: "cv-02",
      ref: "CV-02",
      type: "pedal",
      brand: "Chevrolet",
      brands: ["Chevrolet"],
      models: ["Corsa", "Sail", "Aveo"],
      title: "Pedal freno y embrague — nervaduras verticales",
      desc: "Forro 100% caucho. Nervaduras verticales. Livianos Chevrolet.",
      tags: ["freno", "embrague", "nervaduras verticales", "liviano"],
      synonyms: ["corsa", "sail", "aveo", "chevy", "chevrolet", "forro pedal"],
      waLine: "pedales",
      legacy: ["P006"],
    },
    {
      id: "cv-03",
      ref: "CV-03",
      type: "pedal",
      brand: "Chevrolet",
      brands: ["Chevrolet", "Mazda", "Suzuki"],
      models: ["Sprint", "Swift", "N300", "N200", "Mazda 323"],
      title: "Pedal freno y embrague — burbujas / panal",
      desc: "Textura burbujas/panal. Chevrolet/Suzuki-line y Mazda 323.",
      tags: ["freno", "embrague", "burbujas", "panal"],
      synonyms: ["sprint", "swift", "n300", "n200", "mazda 323", "323", "spark", "forro pedal"],
      waLine: "pedales",
      legacy: ["P001"],
    },
    {
      id: "cv-04",
      ref: "CV-04",
      type: "pedal",
      brand: "Chevrolet",
      brands: ["Chevrolet"],
      models: ["NPR", "NHR", "NKR"],
      title: "Pedal freno y embrague — Brake/Clutch text",
      desc: "Para camiones Chevrolet NPR / NHR / NKR. Texto Brake/Clutch.",
      tags: ["freno", "embrague", "camion", "brake", "clutch"],
      synonyms: ["npr", "nhr", "nkr", "nqr", "nnr", "camion", "chevy", "chevrolet"],
      waLine: "pedales",
      legacy: ["P010"],
    },
    {
      id: "cv-05",
      ref: "CV-05",
      type: "pedal",
      brand: "Renault",
      brands: ["Renault"],
      models: ["Logan", "Symbol", "Kangoo", "Duster"],
      title: "Pedal freno y embrague — nervaduras horizontales",
      desc: "Renault Logan, Symbol, Kangoo, Duster y otros. Nervaduras horizontales.",
      tags: ["freno", "embrague", "nervaduras horizontales"],
      synonyms: ["logan", "symbol", "kangoo", "duster", "renault", "sandero", "clio", "forro pedal"],
      waLine: "pedales",
      legacy: ["P003", "P004"],
    },
    {
      id: "cv-06",
      ref: "CV-06",
      type: "pedal",
      brand: "Kia",
      brands: ["Kia", "Hyundai", "Mitsubishi"],
      models: ["Kia Rio", "Sportage", "Sorento", "Hyundai Accent", "Vision", "Mitsubishi L300"],
      title: "Pedal freno y embrague — espiga / chevron",
      desc: "Textura espiga/chevron. Kia, Hyundai Accent/Vision y Mitsubishi L300.",
      tags: ["freno", "embrague", "espiga", "chevron"],
      synonyms: ["rio", "sportage", "sorento", "accent", "acent", "vision", "l300", "kia", "hyundai", "mitsubishi"],
      waLine: "pedales",
      legacy: ["P005", "P007"],
    },
    {
      id: "cv-07",
      ref: "CV-07",
      type: "pedal",
      brand: "Hyundai",
      brands: ["Hyundai", "Kia", "Mazda"],
      models: ["i10", "Picanto", "Mazda", "Lion"],
      title: "Pedal freno y embrague — nervaduras verticales",
      desc: "Hyundai i10, Kia Picanto/Lion y Mazda. Nervaduras verticales.",
      tags: ["freno", "embrague", "nervaduras verticales"],
      synonyms: ["i10", "picanto", "lion", "mazda", "hyundai", "kia", "forro pedal"],
      waLine: "pedales",
      legacy: ["P005"],
    },
    {
      id: "cv-08",
      ref: "CV-08",
      type: "pedal",
      brand: "Hyundai",
      brands: ["Hyundai"],
      models: ["Atos"],
      title: "Pedal freno y embrague — espiga (Atos)",
      desc: "Hyundai Atos. Textura espiga.",
      tags: ["freno", "embrague", "espiga", "atos"],
      synonyms: ["atos", "hyundai", "taxi", "forro pedal"],
      waLine: "pedales",
      legacy: ["P002"],
    },
    {
      id: "cv-09",
      ref: "CV-09",
      type: "pedal",
      brand: "Hyundai",
      brands: ["Hyundai"],
      models: ["Accent"],
      title: "Pedal freno y embrague — nervaduras verticales",
      desc: "Hyundai Accent y otros. Nervaduras verticales.",
      tags: ["freno", "embrague", "nervaduras verticales"],
      synonyms: ["accent", "acent", "acento", "hyundai", "forro pedal"],
      waLine: "pedales",
      legacy: ["P002", "P005"],
    },
    {
      id: "cv-10",
      ref: "CV-10",
      type: "pedal",
      brand: "Nissan",
      brands: ["Nissan"],
      models: ["Frontier", "Urvan"],
      title: "Pedal freno y embrague — rejilla / bloques",
      desc: "Nissan Frontier y Urvan. Textura rejilla/bloques. Ref. también CV101.",
      tags: ["freno", "embrague", "rejilla", "camioneta"],
      synonyms: ["frontier", "urvan", "navarra", "nissan", "cv101", "forro pedal"],
      waLine: "pedales",
      legacy: ["P008"],
    },
    {
      id: "cv-11",
      ref: "CV-11",
      type: "pedal",
      brand: "Nissan",
      brands: ["Nissan", "Mercedes-Benz"],
      models: ["Busetón Nissan", "Mercedes-Benz", "Esplínder"],
      title: "Pedal freno y embrague — espiga (bus)",
      desc: "Busetón Nissan, Mercedes-Benz y Esplínder. Textura espiga.",
      tags: ["freno", "embrague", "espiga", "bus"],
      synonyms: ["buseton", "busetón", "mercedes", "mercedes-benz", "esplinder", "esplínder", "nissan", "bus"],
      waLine: "pedales",
    },
    {
      id: "cv-12",
      ref: "CV-12",
      type: "pedal",
      brand: "Toyota",
      brands: ["Toyota"],
      models: ["Universal", "Prado", "4Runner"],
      title: "Pedal freno y embrague — mixto (Toyota)",
      desc: "Toyota universal, Prado, 4Runner y otros. Textura mixta.",
      tags: ["freno", "embrague", "mixto", "camioneta"],
      synonyms: ["prado", "4runner", "runner", "fortuner", "hilux", "tacoma", "toyota", "land cruiser", "forro pedal"],
      waLine: "pedales",
      legacy: ["P011"],
    },

    // ——— GUARDAPOLVOS / FUELLES — RENAULT ———
    {
      id: "ren-gp-eje-lc-classic",
      ref: "GP-REN-EJE-LC",
      type: "guardapolvo",
      brand: "Renault",
      brands: ["Renault"],
      models: ["R4 Master/Lider", "R6", "R9", "R12", "R18", "R19", "Clio I"],
      title: "Guardapolvo eje L/C — junta triceta / homocinética",
      desc: "G/POLVO eje L/C. R4, R6, R9, R12, R18, R19, Clio I (catálogo cauchos).",
      tags: ["guardapolvo", "eje", "L/C", "triceta", "homocinetica"],
      synonyms: ["guardapolvo", "fuelle eje", "homocinetica", "homocinética", "triceta", "renault", "r4", "r9", "r19", "clio"],
      waLine: "fuelles",
    },
    {
      id: "ren-gp-eje-lr-classic",
      ref: "GP-REN-EJE-LR",
      type: "guardapolvo",
      brand: "Renault",
      brands: ["Renault"],
      models: ["R4", "R6", "R12", "R18", "R19", "Logan", "Megane II", "Sandero I", "Grand Scenic", "Scenic II", "Stepway I"],
      title: "Guardapolvo eje L/R — triceta / homocinética",
      desc: "G/POLVO eje L/R. Clásicos Renault + Logan, Megane II, Sandero, Scenic, Stepway.",
      tags: ["guardapolvo", "eje", "L/R", "triceta"],
      synonyms: ["guardapolvo", "eje", "logan", "sandero", "megane", "scenic", "stepway", "renault"],
      waLine: "fuelles",
    },
    {
      id: "ren-gp-eje-lc-lh-modern",
      ref: "GP-REN-EJE-LC-LH",
      type: "guardapolvo",
      brand: "Renault",
      brands: ["Renault"],
      models: [
        "Clio I 1.4/1.8 8v (92/01)",
        "Clio II 1.4/1.6 16v (01/12)",
        "Megane I 1.4/1.6 16v (99/09)",
        "Citius Taxi 1.4 16v (06/10)",
        "Symbol I 1.4 8v (01/03)",
        "Symbol II 1.4/1.6 16v (03/10)",
        "Logan 1.4/1.6 8v (05-16)",
        "Logan 1.6 Fase II (16-)",
        "Sandero I 1.6 8v-16v (09-16)",
        "Sandero II 1.6 (16-)",
      ],
      title: "Guardapolvo eje L/C LH — Clio · Megane · Logan · Sandero · Taxi",
      desc: "G/POLVO eje L/C izquierdo LH. Logan/Sandero Fase II: SIN GRASA / SIN ABRAZADERAS (según PDF).",
      tags: ["guardapolvo", "eje", "L/C", "LH", "taxi"],
      synonyms: ["clio", "megane", "citius", "symbol", "logan", "sandero", "taxi", "renault", "guardapolvo"],
      waLine: "fuelles",
      notes: "Logan 1.6 Fase II y Sandero II: sin grasa / sin abrazaderas",
    },
    {
      id: "ren-gp-duster",
      ref: "GP-REN-DUSTER",
      type: "guardapolvo",
      brand: "Renault",
      brands: ["Renault"],
      models: [
        "Duster 1.6/2.0 2WD (12-)",
        "Duster 2.0 4WD (12-)",
        "Duster Oroch 2.0 2WD (16-)",
        "Fluence 1.6/2.0 (10/15)",
      ],
      title: "Guardapolvo eje — Duster / Oroch / Fluence",
      desc: "G/POLVO eje L/C solo y L/R. Duster 2WD/4WD, Oroch y Fluence.",
      tags: ["guardapolvo", "eje", "duster", "camioneta"],
      synonyms: ["duster", "oroch", "fluence", "renault", "4wd", "2wd", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "ren-fuelle-dir",
      ref: "FU-REN-DIR",
      type: "fuelle",
      brand: "Renault",
      brands: ["Renault"],
      models: [
        "R4 Master/Lider",
        "R18",
        "R9",
        "Twingo I",
        "Twingo II",
        "Clio I",
        "Clio II",
        "Clio II Campus",
        "Express Taxi",
        "Kangoo",
        "Megane I",
        "Scenic I",
        "Citius Taxi",
        "Symbol I",
        "Symbol II",
      ],
      title: "Fuelle caja dirección — Renault",
      desc: "Fuelle de caja de dirección. Amplia cobertura Renault liviano y taxi.",
      tags: ["fuelle", "direccion", "caja direccion"],
      synonyms: ["fuelle", "direccion", "dirección", "cremallera", "twingo", "clio", "kangoo", "symbol", "renault", "taxi"],
      waLine: "fuelles",
    },

    // ——— MAZDA ———
    {
      id: "maz-gp-626-lr-grasa",
      ref: "GP-MAZ-626-LR",
      type: "guardapolvo",
      brand: "Mazda",
      brands: ["Mazda"],
      models: ["626 Nueva Raza 1.8 (84/88)", "MX-6 2.0 16v (93/97)"],
      title: "Guardapolvo L/R con grasa — 626 NR / MX-6",
      desc: "G/POLVO L/R con grasa. 626 Nueva Raza y MX-6.",
      tags: ["guardapolvo", "L/R", "grasa", "626"],
      synonyms: ["mazda", "626", "mx-6", "mx6", "nueva raza", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "maz-gp-626-lc",
      ref: "GP-MAZ-626-LC",
      type: "guardapolvo",
      brand: "Mazda",
      brands: ["Mazda"],
      models: ["626 Nueva Raza 1.8 (84/88)"],
      title: "Guardapolvo L/C — 626 Nueva Raza",
      desc: "G/POLVO L/C. 626 Nueva Raza 1.8 (84/88).",
      tags: ["guardapolvo", "L/C", "626"],
      synonyms: ["mazda", "626", "nueva raza", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "maz-gp-626-asahi",
      ref: "GP-MAZ-626-ASAHI",
      type: "guardapolvo",
      brand: "Mazda",
      brands: ["Mazda"],
      models: [
        "626 Asahi 1.8/2.0 (89/97)",
        "Matsuri 2.0 16v (93/97)",
        "Nuevo Milenio 2.0 16v",
      ],
      title: "Guardapolvo L/R + L/C — 626 Asahi / Matsuri / Nuevo Milenio",
      desc: "G/POLVO L/R y L/C. 626 Asahi, Matsuri y Nuevo Milenio.",
      tags: ["guardapolvo", "L/R", "L/C", "626", "asahi"],
      synonyms: ["mazda", "626", "asahi", "matsuri", "nuevo milenio", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "maz-fuelle-mx6",
      ref: "FU-MAZ-32113",
      type: "fuelle",
      brand: "Mazda",
      brands: ["Mazda"],
      models: ["MX-6 2.0 16v (93/97)"],
      title: "Fuelle dirección COD 32113 · REF GJ2232125",
      desc: "Fuelle de dirección. Código 32113, referencia GJ2232125. MX-6 2.0 16v.",
      tags: ["fuelle", "direccion", "32113", "GJ2232125"],
      synonyms: ["mazda", "mx-6", "mx6", "fuelle", "direccion", "32113", "gj2232125"],
      waLine: "fuelles",
    },
    {
      id: "maz-gp-mazda3",
      ref: "GP-MAZ-M3-HEX",
      type: "guardapolvo",
      brand: "Mazda",
      brands: ["Mazda"],
      models: [
        "Mazda3 1.6/2.0 (04/14)",
        "Mazda3 All New (11/14)",
        "Mazda5 2.0 (06/08)",
        "Mazda5 All New (11/12)",
      ],
      title: "Guardapolvo L/C base hexagonal (AT) — Mazda3 / Mazda5",
      desc: "G/POLVO L/C base hexagonal (automática). Mazda3 y Mazda5.",
      tags: ["guardapolvo", "L/C", "hexagonal", "AT"],
      synonyms: ["mazda3", "mazda 3", "mazda5", "mazda 5", "hexagonal", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "maz-gp-b2600",
      ref: "GP-MAZ-B2600",
      type: "guardapolvo",
      brand: "Mazda",
      brands: ["Mazda"],
      models: ["B2600 2.6 12v 4WD (92/07)"],
      title: "Guardapolvo L/R + L/C — B2600 4WD",
      desc: "G/POLVO L/R y L/C. Mazda B2600 2.6 12v 4WD.",
      tags: ["guardapolvo", "camioneta", "4WD", "B2600"],
      synonyms: ["b2600", "mazda", "4wd", "camioneta", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "maz-brand-cotizar",
      ref: "GP-MAZ-COTIZAR",
      type: "guardapolvo",
      brand: "Mazda",
      brands: ["Mazda"],
      models: ["Cotizar por modelo"],
      title: "Guardapolvos / fuelles Mazda — cotizar por modelo",
      desc: "Página de marca en catálogo PDF. Indique modelo exacto por WhatsApp.",
      tags: ["guardapolvo", "fuelle", "cotizar"],
      synonyms: ["mazda", "cotizar", "modelo", "guardapolvo", "fuelle"],
      waLine: "fuelles",
    },

    // ——— CHEVROLET / SUZUKI-line ———
    {
      id: "chevy-gp-aveo-optra-sail",
      ref: "GP-CHEV-AVEO-LC",
      type: "guardapolvo",
      brand: "Chevrolet",
      brands: ["Chevrolet"],
      models: ["Aveo T200/T250", "Optra J200", "Sail 1.4"],
      title: "Guardapolvo eje L/C sin grasa — Aveo · Optra · Sail",
      desc: "G/POLVO L/C sin grasa. Aveo T200/T250, Optra J200, Sail.",
      tags: ["guardapolvo", "L/C", "sin grasa"],
      synonyms: ["aveo", "optra", "sail", "chevrolet", "chevy", "t200", "t250", "j200", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "chevy-gp-aveo-lr",
      ref: "GP-CHEV-AVEO-LR",
      type: "guardapolvo",
      brand: "Chevrolet",
      brands: ["Chevrolet"],
      models: ["Aveo T200/T250", "Captiva", "Optra J200", "Sail"],
      title: "Guardapolvo eje L/R — Aveo · Captiva · Optra · Sail",
      desc: "G/POLVO eje L/R. Aveo, Captiva, Optra y Sail (catálogo cauchos).",
      tags: ["guardapolvo", "L/R"],
      synonyms: ["aveo", "captiva", "optra", "sail", "chevrolet", "chevy", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "chevy-gp-spark",
      ref: "GP-CHEV-SPARK",
      type: "guardapolvo",
      brand: "Chevrolet",
      brands: ["Chevrolet", "Suzuki"],
      models: ["Spark I M200", "Spark II Chronos M250", "Alto 1.0", "Swift", "Sprint SA310"],
      title: "Guardapolvo L/R y L/C CON grasa+abrazaderas — Spark · Alto · Swift",
      desc: "Spark I/II Chronos: L/R y L/C CON grasa y abrazaderas. También Alto, Swift, Sprint.",
      tags: ["guardapolvo", "L/R", "L/C", "grasa", "abrazaderas"],
      synonyms: ["spark", "chronos", "alto", "swift", "sprint", "m200", "m250", "chevrolet", "suzuki", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "chevy-fuelle-sprint",
      ref: "FU-CHEV-SPRINT-RH",
      type: "fuelle",
      brand: "Chevrolet",
      brands: ["Chevrolet", "Suzuki"],
      models: ["Sprint SA310", "Alto 1.0", "Swift 1.0/1.3/1.6"],
      title: "Fuelle dirección lado pasajero RH — Sprint · Alto · Swift",
      desc: "Fuelle caja dirección lado pasajero. Sprint SA310, Alto y Swift.",
      tags: ["fuelle", "direccion", "RH", "pasajero"],
      synonyms: ["sprint", "sa310", "alto", "swift", "fuelle", "direccion", "chevrolet", "suzuki"],
      waLine: "fuelles",
    },
    {
      id: "chevy-fuelle-dir-lh",
      ref: "FU-CHEV-DIR-LH",
      type: "fuelle",
      brand: "Chevrolet",
      brands: ["Chevrolet", "Suzuki"],
      models: ["Alto", "Sprint SA310", "Swift"],
      title: "Fuelle dirección lado conductor LH — Alto · Sprint · Swift",
      desc: "Fuelle caja dirección lado conductor [LH].",
      tags: ["fuelle", "direccion", "LH", "conductor"],
      synonyms: ["alto", "sprint", "swift", "fuelle", "direccion", "chevrolet"],
      waLine: "fuelles",
    },
    {
      id: "chevy-fuelle-corsa-hid",
      ref: "FU-CHEV-CORSA-HID",
      type: "fuelle",
      brand: "Chevrolet",
      brands: ["Chevrolet"],
      models: ["Corsa", "Aveo", "Spark", "Captiva", "Onix", "Sail", "Optra"],
      title: "Fuelle dirección hidráulica — Corsa / multi Chevy",
      desc: "Fuelle caja dirección hidráulica Corsa y línea Aveo/Spark/Captiva/Onix/Sail/Optra (SER11006 der.).",
      tags: ["fuelle", "direccion", "hidraulica"],
      synonyms: ["corsa", "aveo", "spark", "captiva", "onix", "sail", "optra", "hidraulica", "fuelle", "chevrolet"],
      waLine: "fuelles",
    },
    {
      id: "chevy-gp-corsa",
      ref: "GP-CHEV-CORSA",
      type: "guardapolvo",
      brand: "Chevrolet",
      brands: ["Chevrolet"],
      models: ["Chevy C2", "Corsa 1ª fase", "Corsa (98/05)", "Corsa Diesel Taxi"],
      title: "Guardapolvo eje L/R · L/C — Corsa / Chevy C2 / Taxi",
      desc: "G/POLVO eje. Chevy C2, Corsa fases y Corsa Diesel taxi.",
      tags: ["guardapolvo", "taxi", "corsa"],
      synonyms: ["corsa", "chevy c2", "taxi", "diesel", "chevrolet", "guardapolvo"],
      waLine: "fuelles",
    },
    {
      id: "chevy-gp-camioneta",
      ref: "GP-CHEV-CAMIONETA",
      type: "guardapolvo",
      brand: "Chevrolet",
      brands: ["Chevrolet", "Suzuki"],
      models: [
        "Trooper 2.6 4WD",
        "LUV 1600",
        "LUV 2200",
        "LUV 2300",
        "LUV 2800",
        "Vitara SE416",
        "D-Max RT50",
      ],
      title: "Guardapolvo eje — Trooper · LUV · Vitara · D-Max RT50",
      desc: "G/POLVO eje L/R y L/C. Camionetas Chevrolet/Suzuki-line y D-Max RT50.",
      tags: ["guardapolvo", "camioneta", "4WD"],
      synonyms: ["trooper", "luv", "vitara", "d-max", "dmax", "rt50", "rt-50", "chevrolet", "guardapolvo"],
      waLine: "fuelles",
    },

    // ——— HYUNDAI / KIA TAXI ———
    {
      id: "hyu-gp-atos-taxi",
      ref: "GP-HYU-ATOS",
      type: "guardapolvo",
      brand: "Hyundai",
      brands: ["Hyundai"],
      models: ["Atos I", "Atos II"],
      title: "Guardapolvo L/R y L/C con grasa — Hyundai Taxi Atos",
      desc: "G/POLVO L/R y L/C con grasa. Hyundai Taxi Atos I/II.",
      tags: ["guardapolvo", "taxi", "grasa", "atos"],
      synonyms: ["atos", "hyundai", "taxi", "guardapolvo", "grasa"],
      waLine: "fuelles",
    },
    {
      id: "hyu-fuelle-i10",
      ref: "FU-HYU-I10",
      type: "fuelle",
      brand: "Hyundai",
      brands: ["Hyundai"],
      models: ["i10"],
      title: "Fuelle de dirección — Hyundai i10",
      desc: "Fuelle de dirección Hyundai i10 (página Hyundai & Kia Taxi del PDF).",
      tags: ["fuelle", "direccion", "i10"],
      synonyms: ["i10", "hyundai", "fuelle", "direccion", "taxi"],
      waLine: "fuelles",
    },
    {
      id: "kia-gp-picanto-lr",
      ref: "33103",
      type: "guardapolvo",
      brand: "Kia",
      brands: ["Kia"],
      models: ["Eko Taxi I/II", "Picanto I", "Picanto II Morning"],
      title: "Guardapolvo L/R · Cód. 33103 · Ref 4411882012",
      desc: "G/POLVO L/R. Kia Picanto / Ekotaxi / Ion. Código 33103, ref 4411882012.",
      tags: ["guardapolvo", "L/R", "taxi", "33103"],
      synonyms: ["picanto", "ekotaxi", "eko taxi", "ion", "morning", "kia", "33103", "4411882012", "taxi"],
      waLine: "fuelles",
    },
    {
      id: "kia-gp-picanto-lc",
      ref: "33104",
      type: "guardapolvo",
      brand: "Kia",
      brands: ["Kia"],
      models: ["Eko Taxi I/II", "Picanto I", "Picanto II Morning"],
      title: "Guardapolvo L/C · Cód. 33104 · Ref 4411982012",
      desc: "G/POLVO L/C. Kia Picanto / Ekotaxi / Ion. Código 33104, ref 4411982012.",
      tags: ["guardapolvo", "L/C", "taxi", "33104"],
      synonyms: ["picanto", "ekotaxi", "eko taxi", "ion", "morning", "kia", "33104", "4411982012", "taxi"],
      waLine: "fuelles",
    },

    // ——— MEZCLAS ———
    {
      id: "mez-pedal",
      ref: "MEZ-PEDAL",
      type: "mezcla",
      brand: "",
      brands: [],
      models: [],
      title: "Caucho pedal",
      desc: "Compuesto para forros de pedal. Buena adherencia y agarre.",
      tags: ["mezcla", "compuesto", "pedal"],
      synonyms: ["mezcla", "compuesto", "caucho pedal", "forro", "molino"],
      waLine: "mezclas",
    },
    {
      id: "mez-campana",
      ref: "MEZ-CAMPANA",
      type: "mezcla",
      brand: "",
      brands: [],
      models: [],
      title: "Caucho campana — dureza y aguante 100",
      desc: "Línea campana: dureza y aguante altos.",
      tags: ["mezcla", "campana", "dureza 100"],
      synonyms: ["campana", "dureza", "aguante", "mezcla", "compuesto"],
      waLine: "mezclas",
    },
    {
      id: "mez-nitrilo",
      ref: "MEZ-NBR",
      type: "mezcla",
      brand: "",
      brands: [],
      models: [],
      title: "Caucho nitrilo (NBR)",
      desc: "Para piezas en contacto con aceites: sellos, mangueras, diafragmas.",
      tags: ["mezcla", "nitrilo", "NBR"],
      synonyms: ["nitrilo", "nbr", "aceite", "sello", "mezcla"],
      waLine: "mezclas",
    },
    {
      id: "mez-rayox",
      ref: "MEZ-RAYOX",
      type: "mezcla",
      brand: "",
      brands: [],
      models: [],
      title: "Caucho plomo Rayox X",
      desc: "Línea Rayox X. Cotizar según muestra o ficha.",
      tags: ["mezcla", "rayox", "plomo"],
      synonyms: ["rayox", "plomo", "mezcla", "compuesto"],
      waLine: "mezclas",
    },
    {
      id: "mez-diafragmas",
      ref: "MEZ-DIAF",
      type: "mezcla",
      brand: "",
      brands: [],
      models: [],
      title: "Caucho diafragmas",
      desc: "Compuesto para diafragmas y membranas.",
      tags: ["mezcla", "diafragmas"],
      synonyms: ["diafragma", "membrana", "mezcla"],
      waLine: "mezclas",
    },
    {
      id: "mez-bujes",
      ref: "MEZ-BUJES",
      type: "mezcla",
      brand: "",
      brands: [],
      models: [],
      title: "Caucho bujes",
      desc: "Para bujes y topes de caucho. Suspensión y amortiguación.",
      tags: ["mezcla", "bujes"],
      synonyms: ["buje", "bujes", "tope", "suspension", "mezcla"],
      waLine: "mezclas",
    },
    {
      id: "mez-medida",
      ref: "MEZ-MEDIDA",
      type: "mezcla",
      brand: "",
      brands: [],
      models: [],
      title: "Compuestos a medida",
      desc: "Mezclas y maquila según pieza o ficha. Pedidos B2B desde Bogotá.",
      tags: ["mezcla", "a medida", "maquila"],
      synonyms: ["medida", "maquila", "custom", "pedido", "mezcla", "compuesto"],
      waLine: "mezclas",
    },
  ];

  global.VA_CATALOG = {
    brands,
    products,
    waLines: WA_LINES,
    waNumber: "573114560990",
  };
})(typeof window !== "undefined" ? window : globalThis);
